language: csharp
dist: bionic
dotnet: 3.1.100
mono:
  - latest
  - 6.8.0
  - 5.20.0
  # Mono 5.4.1 (31 Oct 2017)
  - 5.4.1
  - 4.8.1
os:
  - linux
  - osx
solution: NetLicensingClient.sln
script:
  - dotnet restore
  # see also http://www.mono-project.com/FAQ:_Security
  - mozroots --import --ask-remove
  - xbuild NetLicensingClient.sln
  - mono NetLicensingClient-demo/bin/Debug/NetLicensingClient-demo.exe
