language: csharp
dist: bionic
dotnet: 3.1.302
mono:
  - latest
  - 5.20.1
  - 4.8.1
os:
  - linux
solution: NetLicensingClient.sln
install:
  - dotnet restore
script:
  - dotnet build -c Release
after_success:
  - dotnet run --project NetLicensingClient-demo
jobs:
  include:
  - stage: nuget push
    script:
    - if [ -n "$TRAVIS_TAG" ]; then echo "Push version ${TRAVIS_TAG} to NuGet...";
      fi
    before_deploy:
      - dotnet pack -p:PackageVersion=${TRAVIS_TAG} -c Release
    deploy:
      skip_cleanup: true
      provider: script
      script: dotnet nuget push ./NetLicensingClient/bin/Release/NetLicensingClient*.nupkg -k $NUGET_API -s https://api.nuget.org/v3/index.json --skip-duplicate
      on:
        tags: true
