language: csharp
mono:
  - latest
os:
  - linux
  - osx
solution: NetLicensingClient.sln
script:
  # see also http://www.mono-project.com/FAQ:_Security
  - mozroots --import --ask-remove
  - xbuild NetLicensingClient.sln
  - mono NetLicensingClient-demo/bin/Debug/NetLicensingClient-demo.exe
