language: csharp
solution: NetLicensingClient.sln
dotnet: 2.1.505
mono:
  - latest
  - 5.18.1
  - 5.4.1
os:
  - linux
  - osx
script:
  - dotnet restore
  # see also http://www.mono-project.com/FAQ:_Security
  - mozroots --import --ask-remove
  - xbuild NetLicensingClient.sln
  - mono NetLicensingClient-demo/bin/Debug/NetLicensingClient-demo.exe
  - mkdir .nuget
  - curl https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -o ./.nuget/nuget.exe
  - mono ./.nuget/nuget.exe pack "./NetLicensingClient/NetLicensingClient.csproj" -Build -Symbols -Properties Configuration=Release -OutputFileNamesWithoutVersion -OutputDirectory "./NetLicensingClient/bin/Release/"
  - mono ./.nuget/nuget.exe push "./NetLicensingClient/bin/Release/NetLicensingClient.nupkg" -ApiKey $NUGET_PUSH_KEY -Source "https://api.nuget.org/v3/index.json" -SkipDuplicate
