language: csharp
dist: bionic
dotnet: 3.1.302
mono:
  - latest
  - 5.20.1
  - 4.8.1
os:
  - linux
solution: NetLicensingClient.sln
script:
  - dotnet restore
  # see also http://www.mono-project.com/FAQ:_Security
  - mozroots --import --ask-remove --sync
  - xbuild NetLicensingClient.sln
  - mono NetLicensingClient-demo/bin/Debug/NetLicensingClient-demo.exe
