language: csharp
dist: bionic
dotnet: 3.1.302
mono:
  - latest
  - 5.20.1
  - 4.8.1
os:
  - linux
solution: NetLicensingClient.sln
install:
  - dotnet restore
script:
  - dotnet build -c Release
after_success:
  - mono NetLicensingClient-demo/bin/Release/netcoreapp3.1/NetLicensingClient-demo.dll
before_deploy:
  - dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push ./NetLicensingClient/bin/Release/NetLicensingClient*.nupkg -k $NUGET_API -s https://api.nuget.org/v3/index.json --skip-duplicate
  on:
    branch: master
