language: csharp
dist: bionic
dotnet: 3.1.100
mono:
  - latest
  - 6.8.0
  # Use Mono 5.20.0 (11 Apr 2019) instead
  - 5.18.1
  - 4.8.1
os:
  - linux
  - osx
solution: NetLicensingClient.sln
script:
  - dotnet restore
  # see also http://www.mono-project.com/FAQ:_Security
  - mozroots --import --ask-remove
  - xbuild NetLicensingClient.sln
  - mono NetLicensingClient-demo/bin/Debug/NetLicensingClient-demo.exe
