// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace NetLicensingDemo {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Table tbl1;
		
		protected System.Web.UI.WebControls.TextBox textHardwareId;
		
		protected System.Web.UI.WebControls.Button buttonGetLicenseeNumber;
		
		protected System.Web.UI.WebControls.TextBox textLicenseeNumber;
		
		protected System.Web.UI.WebControls.Button buttonValidate;
		
		protected System.Web.UI.WebControls.Table tblP1;
		
		protected System.Web.UI.WebControls.TextBox textTryBuy;
		
		protected System.Web.UI.WebControls.Table tblP2;
		
		protected System.Web.UI.WebControls.TextBox textSubscription;
		
		protected System.Web.UI.WebControls.Label message;
	}
}
